ABG/Controllers/WebSiteController.cs
using System;
using System.Linq;
using System.Web.Mvc;

namespace ABG.Controllers
{
    public class WebSiteController : Controller
    {
        public WebSiteController()
        {
            string Message = "";
            string CacBanTinThue = Article_Data.CateChildKey(Helper.PartnerNumber, out Message, 38);
            ViewBag.TinChoThueMoiNhat = Article_Data.ListInCate(Helper.PartnerNumber, out Message, CacBanTinThue).Take(5).ToList();
            string CacBanGioiThieu = Article_Data.CateChildKey(Helper.PartnerNumber, out Message, 39);
            var danhsach = Article_Data.ListInCate(Helper.PartnerNumber, out Message, CacBanGioiThieu);
            ViewBag.GioiThieuCty = danhsach.Where(s => s.CategoryKey == 48 && s.Publish == true).OrderByDescending(s => s.CreatedOn).FirstOrDefault();
            ViewBag.GioiThieuKho = danhsach.Where(s => s.CategoryKey == 60 && s.Publish == true).OrderByDescending(s => s.CreatedOn).FirstOrDefault();
            ViewBag.GioiThieuXeNang = danhsach.Where(s => s.CategoryKey == 61 && s.Publish == true).OrderByDescending(s => s.CreatedOn).FirstOrDefault();
            ViewBag.GioiThieuXangDau = danhsach.Where(s => s.CategoryKey == 62 && s.Publish == true).OrderByDescending(s => s.CreatedOn).FirstOrDefault();

            var allowedStatus = new[] { 49, 50, 52, 53, 54 };
            ViewBag.CacDiaDiem = danhsach.Where(s => allowedStatus.Contains(s.CategoryKey)).ToList();

            ViewBag.LinkYoutube = new Article_Info("8a428fdd-e7e2-49a6-b29b-b85e0edfbe7b").Article.Summarize;
            ViewBag.LienHe = new Article_Info("87818f9e-a306-47bc-87df-0a8e2c60e679").Article.Summarize;
            ViewBag.ThongtinCty = new Article_Info("2d1b1a44-2c32-401c-b357-db5535ce01d8").Article.Summarize;
        }

        // GET: WebSite
        public ActionResult Index()
        {
            return RedirectToAction("trangchu");
        }

        public ActionResult lienhe()
        {
            return View();
        }

        [HttpPost]
        public JsonResult guilienhe(string name, string email, string subject, string message)
        {
            ServerResult zResult = new ServerResult();
            Comment_Info zInfo = new Comment_Info();
            zInfo.Comment.CustomerName = name.Trim();
            zInfo.Comment.CustomerEmail = email.Trim();
            zInfo.Comment.CommentDate = DateTime.Now;
            zInfo.Comment.CommentID = subject;
            zInfo.Comment.Description = message;
            zInfo.Comment.PartnerNumber = Helper.PartnerNumber;
            zInfo.Create_ServerKey();

            if (zInfo.Code == "200" || zInfo.Code == "201")
            {
                zResult.Success = true;
                zResult.Message = "Thông tin của quí khách đã được gửi đến phòng kinh doanh !.";
            }
            else
            {
                zResult.Success = false;
                zResult.Message = zInfo.Message.GetFirstLine();
            }
            return Json(zResult, JsonRequestBehavior.AllowGet);
        }

        public ActionResult trangchu()
        {
            ViewBag.List = Article_Data.List(Helper.PartnerNumber, out string Message, 0);
            return View();
        }

        public ActionResult slideHinhAnh()
        {
            ViewBag.ListBanner = Banner_Data.List(Helper.PartnerNumber, out string Message);
            return PartialView("~/Views/WebSite/_SlideHinhAnh.cshtml");
        }

        public ActionResult danhsachTin(int Category = 0)
        {
            Article_Category_Info zCat = new Article_Category_Info(Category);
            ViewBag.Cate2 = zCat.Article_Category.CategoryName;
            ViewBag.ArticleList = Article_Data.List(Helper.PartnerNumber, out string Message, Category);
            Article_Category_Info zCat1 = new Article_Category_Info(zCat.Article_Category.Parent);
            ViewBag.Cate1 = zCat1.Article_Category.CategoryName;

            if (zCat.Article_Category.Parent != 0)
            {
                Category = zCat.Article_Category.Parent;
            }
                       
            ViewBag.Category = Category;
            return View();
        }

        public ActionResult dichvu(int Parent = 38)
        {
            //mặc định Parent = 38 là các dịch vụ bên kinh doanh
            ViewBag.CateChild = Article_Category_Data.List(Helper.PartnerNumber, out string Message, Parent);
            return PartialView("~/Views/Website/_DichVu.cshtml");
        }

        public ActionResult chitietTin(string ArticleKey = "")
        {
            Article_Info zInfo = new Article_Info(ArticleKey);

            Article_Category_Info zCat = new Article_Category_Info(zInfo.Article.CategoryKey);
            ViewBag.Cate2 = zCat.Article_Category.CategoryName;
            //zCat = new Article_Category_Info(zCat.Article_Category.Parent);
            //ViewBag.Cate1 = zCat.Article_Category.CategoryName;
            ViewBag.Category = zCat.Article_Category.Parent;
            if (zInfo.Code == "200" ||
                zInfo.Code == "201")
            {
                return View(zInfo.Article);
            }
            else
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        public ActionResult allTag()
        {
            ViewBag.List = Article_Data.ListTag(Helper.PartnerNumber, out string Message);
            return PartialView("~/Views/WebSite/_Tag.cshtml");
        }

        public ActionResult thongbaoMoi()
        {
            ViewBag.List = Article_Data.ListNew(Helper.PartnerNumber, out string Message);
            return PartialView("~/Views/WebSite/_Thongbao.cshtml");
        }

        public ActionResult listTag(string Tag)
        {
            ViewBag.ArticleList = Article_Data.ListByTag(Helper.PartnerNumber, out string Message, Tag);
            return View("~/Views/Website/danhsachtin.cshtml");
        }


        public ActionResult coDong(int Category = 0)
        {
            var List = Article_Category_Data.List(Helper.PartnerNumber, out string Message, 37);
            ViewBag.CateList = List = List.OrderByDescending(s => s.CategoryName).ToList();
            int Cate = 0;
            if (Category == 0)
            {
                Cate = List[0].CategoryKey;
                ViewBag.Name = List[0].CategoryName;
            }
            else
            {
                Cate = Category;
                ViewBag.Name = List.Single(s => s.CategoryKey == Category).CategoryName;
            }

            ViewBag.Document = Article_Data.ListDocument(Helper.PartnerNumber, out Message, Cate);
            ViewBag.Image = Article_Data.ListImage(Helper.PartnerNumber, out Message, Cate);
            ViewBag.Category = Category;

            return View("~/Views/Website/codong.cshtml");
        }
    }
}

ABG/Views/WebSite/_DichVu.cshtml
@{ 
    Layout = null;
    var _ListCat = new List<Article_Category_Model>();
    if (ViewBag.CateChild != null)
    {
        _ListCat = ViewBag.CateChild as List<Article_Category_Model>;
    }
}
<ul class="sidebar-link">
    @if (_ListCat.Count > 0)
    {
        foreach (var item in _ListCat)
        {
            <li><a href="@Url.Action("danhsachTin", new { Category = item.CategoryKey })">@item.CategoryName</a></li>
        }
    }
</ul>

ABG/Views/WebSite/_SlideHinhAnh.cshtml
@{ 
    Layout = null;
    var _ListBanner = new List<Banner_Model>();
    if (ViewBag.ListBanner != null)
    {
        _ListBanner = ViewBag.ListBanner as List<Banner_Model>;
    }
}

<div class="intro11-slider-wrap section">
    <div class="intro11-slider swiper-container">
        <div class="swiper-wrapper">
            @{
                foreach (Banner_Model Item in _ListBanner)
                {
                    <div class="single-slide-wrapper swiper-slide slide-1 slide-bg-1 bg-position" style=" background-image: url('@Item.Url'); background-position: center top;">
                        <!-- Intro Content Start -->
                        <div class="slider-content text-center">
                            <h2 class="title" data-splitting>@Item.Title</h2>
                            <h4 class="sub-title">@Item.Description</h4>
                        </div>
                        <!-- Intro Content End -->
                    </div>
                }
            }
        </div>
        <!-- Slider Navigation -->
        <div class="home1-slider-prev swiper-button-prev main-slider-nav"><i class="fa fa-long-arrow-left"></i></div>
        <div class="home1-slider-next swiper-button-next main-slider-nav"><i class="fa fa-long-arrow-right"></i></div>
        <!-- Slider pagination -->
        <div class="swiper-pagination"></div>
    </div>
</div>

ABG/Views/WebSite/_Tag.cshtml
@{
    var Tag = new List<string>();
    if (ViewBag.List != null)
    {
        Tag = ViewBag.List as List<string>;
    }
}
<div class="sidebar-tags">
    @for (int i = 0; i < Tag.Count; i++)
    {
        string tag = Tag[i];
        <a href="@Url.Action("listTag","Website", new { tag })">@tag</a>
    }
</div>

ABG/Views/WebSite/_Thongbao.cshtml
@{ 
    var _List = new List<Article_Model>();
    if (ViewBag.List != null)
    {
        _List = ViewBag.List as List<Article_Model>;
    }
}
<ul class="sidebar-blog">
    @{
        if (_List.Count > 0)
        {
            for (int i = 0; i < _List.Count; i++)
            {
                Article_Model zItem = _List[i];
                string zDate = zItem.CreatedOn.ToString("dd/MM/yyyy");
                <li>
                    <a href="@Url.Action("chitietTin", new { ArticleKey = zItem.ArticleKey })"class="image"><img src="@zItem.ImageLarge" alt="Blog Post"></a>
                    <div class="content">
                        <a class="title" href="@Url.Action("chitietTin", new { ArticleKey = zItem.ArticleKey })">@zItem.ArticleName</a>
                        <span class="date">@zDate</span>
                    </div>
                </li>
            }
        }
    }
</ul>

ABG/Views/WebSite/chitietTin.cshtml
@model Article_Model
@{
    ViewBag.Title = "chitietTin";
    Layout = "~/Views/WebSite/_Layout.cshtml";
    int Parent = 38;
    if (ViewBag.Category != null)
    {
        Parent = ViewBag.Category;
    }
    //string Css = "background: url('/FileUpload/184FDCA5-CCB4-41EC-BE98-85CD3537989B/ArticlePicture/bab23698-d1af-42b8-b36e-4b6a590040ff_z2385232356077_afd8b414faab356c2b5b5876d7b94f30.jpg');background-size: cover;background-repeat: no-repeat;";
    //if (Model.CategoryKey == 48)
    //{
    //    Css = "background: url('/FileUpload/184FDCA5-CCB4-41EC-BE98-85CD3537989B/ArticlePicture/bab23698-d1af-42b8-b36e-4b6a590040ff_z2385232356077_afd8b414faab356c2b5b5876d7b94f30.jpg');background-size: cover;background-repeat: no-repeat;";
    //}
    //else
    //{
    //    if (Model.CategoryKey == 60 ||
    //        Model.CategoryKey == 61 ||
    //        Model.CategoryKey == 62)
    //    {
    //        Css = "background: url('/assets/web/images/dichvu.jpg');background-size: cover;background-repeat: no-repeat; background-position:center;";
    //    }
    //}
}
<div class="breadcrumbs-area position-relative mb-text-p" style="@Helper.ArticleHeaderWebSite">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <div class="breadcrumb-content position-relative section-content">
                    <h3 class="title" style="color:white; text-shadow: rgb(0 0 0) 2px 2px">
                        @ViewBag.Cate2
                    </h3>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<div class="portfolio-section pt-90">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-12 order-lg-2 mt-6 mt-md-0">
               @if (ViewBag.Message != null)
               {
                   <h2 class="text-center">@ViewBag.Message</h2>
               }
                <!-- Portfolio Details Content Start -->
                <div class="portfolio-details-content" data-aos="fade-up" data-aos-delay="300">
                    <div class="portfolio-details-desc mb-8">
                        <h2 class="title text-center">@Model.ArticleName</h2>
                    </div>
                    <div class="mb-3">
                        @Model.Summarize
                    </div>
                    @if (Model.ImageLarge.Length > 0)
                    {
                        <div class="text-center mb-3">
                            <img src="@Url.Content(Model.ImageLarge)" class="fit-image" />
                        </div>
                    }
                    <div class="portfolio-details-info">
                        <ul>
                            <li>
                                @(new HtmlString(Model.ArticleContent))
                            </li>

                            <li class="">
                                <div class="meta-list mb-3">
                                    <a href="#" class="meta-item author">@Model.CreatedName</a>

                                    @if (Model.FileAttack.Length > 0)
                                    {
                                        <a href="@Model.FileAttack" download="" class="float-right" style="font-style: oblique;">
                                            Tập tin đính kèm
                                            <i class="fas fa-paperclip bounce3 animated3 "></i>
                                        </a>
                                    }

                                    <span class="meta-item date">@Model.ModifiedOn.ToString("dd/MM/yyyy")</span>
                                </div>
                                @*
                                    <span>Share</span>
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-instagram"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                    *@
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- Portfolio Details Content End -->
            </div>
            <div class="col-lg-4 col-12 order-lg-1" id="sticky-sidebar">
                <div class="sidebar-wrap">
                    <!--Sidebar Category Start-->
                    <div class="sidebar" data-aos="fade-up" data-aos-delay="300">
                        <h4 class="sidebar-title">Thông báo</h4>
                        <ul class="sidebar-link">
                            @Html.Action("dichvu", "WebSite", new { Parent })
                        </ul>
                    </div>
                    <!--Sidebar Category End-->
                    <!--Sidebar Post Start-->
                    <div class="sidebar" data-aos="fade-up" data-aos-delay="400">
                        <h4 class="sidebar-title">Thông báo mới</h4>
                        @Html.Action("thongbaoMoi", "WebSite")
                    </div>
                    <!--Sidebar Post End-->
                    <!--Sidebar Tags Start-->
                    <div class="sidebar" data-aos="fade-up" data-aos-delay="500">
                        <h4 class="sidebar-title">Từ khóa xem nhanh</h4>
                        @Html.Action("allTag", "WebSite")
                    </div>
                    <!--Sidebar Tags End-->
                </div>
            </div>
        </div>
    </div>
</div>

<!-- nếu là các tin dịch vụ và giới thiệu -->
@if (Model.CategoryKey == 40 ||
       Model.CategoryKey == 41 ||
       Model.CategoryKey == 42 ||
       Model.CategoryKey == 48)
{
    <div class="support-area bg-light pt-90 pb-90 mt-90">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="support-wrapper aos-init aos-animate" data-aos="fade-up" data-aos-delay="300">
                        <div class="section-title text-center">
                            <h1 class="title">Hãy liên hệ với chúng tôi</h1>
                            <div class="mt-5 mb-5 pb-3">
                                <div class="mt-5 mb-5 pb-3">
                                    <p class="text-center">CÔNG TY CỔ PHẦN AN BÌNH</p>
                                    <p class="text-center">Địa chỉ: số 10 Đại lộ Độc Lập, P. An Bình, Tp. Dĩ An, tỉnh Bình Dương</p>
                                    <p class="text-center">Phòng: Kinh doanh</p>
                                    <p class="text-center">Điện thoại: 0937 631384 (Ms. Sương)</p>
                                </div>
                            </div>
                        </div>
                        <div class="support-button">
                            <a class="btn btn-green btn-hover-primary" href="@Url.Action("lienhe","Website")">Liên hệ ngay</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

ABG/Views/WebSite/danhsachTin.cshtml
@{
    ViewBag.Title = "danhsachTin";
    Layout = "~/Views/WebSite/_Layout.cshtml";

    var _ArticleList = new List<Article_Model>();
    if (ViewBag.ArticleList != null)
    {
        _ArticleList = ViewBag.ArticleList as List<Article_Model>;
    }

    int Parent = 38;
    if (ViewBag.Category != null)
    {
        Parent = ViewBag.Category;
    }

    //string Css = "";
    //if (ViewBag.Category >= 43 &&
    //    ViewBag.Category <= 59)
    //{
    //    Css = "background: url('/assets/web/images/banner-news.jpg');background-size: cover;background-repeat: no-repeat;";
    //}

    //if (Request["tag"] != null)
    //{
    //    Css = "background: url('/FileUpload/184FDCA5-CCB4-41EC-BE98-85CD3537989B/ArticlePicture/bab23698-d1af-42b8-b36e-4b6a590040ff_z2385232356077_afd8b414faab356c2b5b5876d7b94f30.jpg');background-size: cover;background-repeat: no-repeat;";
    //}
}
<div class="breadcrumbs-area position-relative mb-text-p" style="@Helper.ArticleHeaderWebSite">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <div class="breadcrumb-content position-relative section-content">
                    <h3 class="title" style="color:white; text-shadow: rgb(0 0 0) 2px 2px">
                        @ViewBag.Cate2
                    </h3>                    
                </div>
            </div>
        </div>
    </div>
</div>
<div class="blog-section pt-90">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-12 order-lg-2">
                <div class="row mb-n10">
                    @{
                        if (_ArticleList.Count > 0)
                        {
                            for (int i = 0; i < _ArticleList.Count; i++)
                            {
                                Article_Model zItem = _ArticleList[i];
                                string zDate = zItem.CreatedOn.ToString("dd/MM/yyyy");
                                string zAuthor = zItem.ModifiedName;
                                string zTitle = zItem.ArticleName;
                                string zSumamarize = zItem.Summarize;
                                string zKey = zItem.ArticleKey;

                                string zImg = zItem.ImageLarge;
                                if (zImg == string.Empty)
                                {
                                    zImg = "~/assets/img/unnamed.png";
                                }

                                <div class="col-sm-6 mb-10">
                                    <!-- Single Blog Post Start -->
                                    <div class="single-blog-post-wrap" data-aos="fade-up" data-aos-delay="200">
                                        <div class="blog-thumbnail" style="text-align:center">
                                            <a href="@Url.Action("chitietTin", new { ArticleKey = zItem.ArticleKey })">
                                                <img style="height:300px" src="@Url.Content(zImg)" alt="Blog Thumb">
                                                <img class="btn-plus" src="@Url.Content("~/assets/web/images/icon/plus.svg")" alt="Plus Icons">
                                            </a>
                                        </div>
                                        <div class="blog-post-details pt-5">
                                            <h3 class="title">
                                                <a href="@Url.Action("chitietTin", new { ArticleKey = zItem.ArticleKey })">
                                                    @zItem.ArticleName
                                                </a>
                                            </h3>
                                            <div class="post-meta mb-3 mt-3">
                                                <a href="@Url.Action("chitietTin", new { ArticleKey = zKey })">
                                                    <i class="fa fa-user"></i> @zAuthor
                                                </a>
                                                <span><i class="fa fa-clock-o"></i> @zDate</span>
                                            </div>
                                            <p class="desc-content desc-content1 mb-2 mb-md-5">@zItem.Summarize</p>
                                            <a href="@Url.Action("chitietTin", new { ArticleKey = zItem.ArticleKey })" class="btn btn-hover-primary read-more">Xem thêm</a>
                                        </div>
                                    </div>
                                    <!-- Single Blog Post End -->
                                </div>
                            }
                        }
                        else
                        {
                            <h3>ĐANG CẬP NHẬT</h3>
                        }
                    }
                </div>
            </div>
            <div class="col-lg-4 col-12 order-lg-1" id="sticky-sidebar">
                <div class="sidebar-wrap">
                    <!--Sidebar Category Start-->
                    <div class="sidebar" data-aos="fade-up" data-aos-delay="300">
                        <h4 class="sidebar-title">Thông báo</h4>
                        <ul class="sidebar-link">
                            @Html.Action("dichvu", "WebSite", new { Parent })
                        </ul>
                    </div>
                    <!--Sidebar Category End-->
                    <!--Sidebar Post Start-->
                    <div class="sidebar" data-aos="fade-up" data-aos-delay="400">
                        <h4 class="sidebar-title">Thông báo mới</h4>
                        @Html.Action("thongbaoMoi", "WebSite")
                    </div>
                    <!--Sidebar Post End-->
                    <!--Sidebar Tags Start-->
                    <div class="sidebar" data-aos="fade-up" data-aos-delay="500">
                        <h4 class="sidebar-title">Từ khóa xem nhanh</h4>
                        @Html.Action("allTag", "WebSite")
                    </div>
                    <!--Sidebar Tags End-->
                </div>
            </div>
        </div>
    </div>
</div>

ABG/Views/WebSite/lienhe.cshtml
@{
    ViewBag.Title = "lienhe";
    Layout = "~/Views/WebSite/_Layout.cshtml";
}

<div class="breadcrumbs-area position-relative mb-text-p" style="@Helper.ArticleHeaderWebSite">
    <div class="container">
        <div class="row">
            <div class="col-12 text-center">
                <div class="breadcrumb-content position-relative section-content">
                    <h3 class="title" style="color:white; text-shadow: rgb(0 0 0) 2px 2px">Liên hệ</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Breadcrumb Area End Here -->
<!-- Contact Information And Title Area Start -->
<div class="contact-info mt-5 pt-90 pb-90">
    <div class="container">
        <div class="row mb-n10">
            <div class="col-md-4 mb-10" data-aos="fade-up" data-aos-delay="100">
                <div class="info">
                    <div class="info-icon">
                        <i class="fa fa-map-marker"></i>
                    </div>
                    <div class="info-content">
                        <h4 class="title">Địa chỉ</h4>
                        <span class="info-text"> Số 10 Đại lộ Độc Lập, KP. Bình Đường 1,<br> P. An Bình, TP. Dĩ An, tỉnh Bình Dương</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-10" data-aos="fade-up" data-aos-delay="300">
                <div class="info">
                    <div class="info-icon">
                        <i class="fa fa-phone"></i>
                    </div>
                    <div class="info-content">
                        <h4 class="title">Điện thoại</h4>
                        <span class="info-text"> 0283 8960964 <br> (Fax) 0283 8960961</span>
                    </div>
                </div>
            </div>
            <div class="col-md-4 mb-10" data-aos="fade-up" data-aos-delay="600">
                <div class="info">
                    <div class="info-icon">
                        <i class="fa fa-envelope-o"></i>
                    </div>
                    <div class="info-content">
                        <h4 class="title">Email</h4>
                        <span class="info-text">
                            <a href="#">absc@anbinhgroup.vn</a>
                            <br>
                            <a href="#">sales@anbinhgroup.vn</a>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Contact Information End -->
<!-- Contact Map Start -->
<div class="contac-map pb-90">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <!--Google Map Area Start-->
                <div class="google-map-area">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d18772.76300544059!2d106.74794823065164!3d10.88036553990921!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3174d87461d72c97%3A0x2f851c58dc9d7f10!2zQ8OUTkcgVFkgQ-G7lCBQSOG6pk4gQU4gQsOMTkg!5e0!3m2!1sen!2sus!4v1615947094148!5m2!1sen!2sus" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>

                </div>
                <!--Google Map Area Start-->
            </div>
        </div>
    </div>
</div>
<!-- Contact Map End -->
<!-- Contact Form Start -->
<div class="contact-form-area bg-light pt-90 pb-90" data-aos="fade-up" data-aos-delay="100">
    <div class="container">
        <div class="row">
            <div class="section-title text-center">
                <h1 class="title">LIÊN HỆ VỚI CHÚNG TÔI</h1>
                <p class="mt-5 mb-5 pb-3">Để biết thêm thông tin chi tiết, vui lòng điền thông tin liên lạc bên dưới và chúng tôi sẽ liên lạc với quí khách sớm nhất</p>
            </div>
            <div class="offset-lg-2 col-lg-8">
                <div class="contact-form">
                    <div>
                        <div class="row">
                            <div class="col-md-6 col-12 mb-6">
                                <input class="input-item" type="text" placeholder="Họ tên *" name="name" id="txt_name">
                            </div>
                            <div class="col-md-6 col-12 mb-6">
                                <input class="input-item" type="email" placeholder="Email *" name="email" id="txt_email">
                            </div>
                            <div class="col-12 mb-6">
                                <input class="input-item" type="text" placeholder="Tiêu đề *" name="subject" id="txt_subject">
                            </div>
                            <div class="col-12 mb-6">
                                <textarea class="textarea-item" name="message" placeholder="Nội dung" id="txt_message"></textarea>
                            </div>
                            <div class="col-12 text-center">
                                <button class="btn btn-primary btn-hover-dark" type="button" id="btnSend">Gửi</button>
                            </div>
                        </div>
                    </div>
                    <p class="form-messege">

                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script>
        var url = "@Url.Action("guilienhe", "WebSite")";
        $("#btnSend").click(function () {
            $.ajax({
            url: url,
            type: 'POST',
            data: {
                "name": $("#txt_name").val(),
                "email": $("#txt_email").val(),
                "subject": $("#txt_subject").val(),
                "message": $("#txt_message").val(),
            },
            beforeSend: function () {
                $(".form-messege").empty();
            },
            success: function (r) {
                $(".form-messege").append(r.Message);
            },
            error: function (err) {
                $(".form-messege").append(err.responseText);
            },
            complete: function () {

            }
        });
        });
    </script>
}